/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Klonoa - Door to Phantomile)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80180C18u
#define func_80180C18 BootEntry  /* alias */
