# psxrecomp_import.py — generated by psxrecomp-analyze
# Ghidra script: creates functions, applies names, and bookmarks the
# indirect sites static analysis could not resolve.
# Run against a project where SLUS_005.85 is loaded at its EXE load address.
# @category PSXRecomp

from ghidra.program.model.symbol import SourceType

fm = currentProgram.getFunctionManager()
st = currentProgram.getSymbolTable()
af = currentProgram.getAddressFactory().getDefaultAddressSpace()

def addr(v):
    return af.getAddress(v)

FUNCS = [
    (0x80180834, 0x240, "func_80180834", "verified"),
    (0x80180A74, 0xA4, "func_80180A74", "verified"),
    (0x80180B18, 0xF8, "func_80180B18", "verified"),
    (0x80180C10, 0x8, "func_80180C10", "high"),
    (0x80180C18, 0xBC, "BootEntry", "low"),
    (0x80180CD4, 0xC, "bios_A0_39_InitHeap", "verified"),
    (0x80180CE4, 0xC, "bios_A0_51_LoadAndExecute", "verified"),
    (0x80180CF4, 0xC, "bios_A0_71_CdInit", "verified"),
    (0x80180D04, 0x54, "func_80180D04", "verified"),
    (0x80180D90, 0x30, "func_80180D90", "verified"),
    (0x80180DC0, 0x10, "func_80180DC0", "high"),
    (0x80180DD0, 0x10, "func_80180DD0", "high"),
    (0x80180DE0, 0xC, "bios_B0_5B_ChangeClearPad", "verified"),
    (0x80180DF0, 0xC, "bios_B0_4A_InitCard", "verified"),
    (0x80180E00, 0xC, "bios_B0_4B_StartCard", "verified"),
    (0x80180E10, 0xC, "bios_B0_4C_StopCard", "verified"),
    (0x80180E78, 0x88, "func_80180E78", "high"),
    (0x80180F30, 0x6C, "func_80180F30", "high"),
    (0x80180FC0, 0xC, "bios_A0_44_FlushCache", "verified"),
    (0x80180FD0, 0x68, "func_80180FD0", "high"),
    (0x8018120C, 0xD0, "func_8018120C", "verified"),
    (0x801812DC, 0x3C, "func_801812DC", "high"),
    (0x80181318, 0xD0, "func_80181318", "medium"),
    (0x801813E8, 0x18, "func_801813E8", "low"),
    (0x80181C04, 0x184, "func_80181C04", "verified"),
    (0x80181E9C, 0x64, "func_80181E9C", "verified"),
    (0x80181FAC, 0x10, "func_80181FAC", "high"),
    (0x80182028, 0x9C, "func_80182028", "verified"),
    (0x801820C4, 0x6C, "func_801820C4", "high"),
    (0x80182130, 0x128, "func_80182130", "verified"),
    (0x80182258, 0x94, "func_80182258", "verified"),
    (0x80182388, 0x64, "func_80182388", "verified"),
    (0x80182514, 0xB8, "func_80182514", "high"),
    (0x801826C4, 0x74, "func_801826C4", "high"),
    (0x80182738, 0x104, "func_80182738", "verified"),
    (0x80182990, 0x4A8, "func_80182990", "high"),
    (0x80183240, 0x290, "func_80183240", "verified"),
    (0x801834D0, 0x58, "func_801834D0", "high"),
    (0x80183528, 0xCC, "func_80183528", "high"),
    (0x801835F4, 0xCC, "func_801835F4", "high"),
    (0x801836C0, 0x44, "func_801836C0", "high"),
    (0x80183704, 0x84, "func_80183704", "high"),
    (0x80183788, 0xB0, "func_80183788", "high"),
    (0x801840E0, 0x4C, "func_801840E0", "low"),
    (0x8018412C, 0x30, "func_8018412C", "high"),
    (0x80184180, 0x2E0, "func_80184180", "medium"),
    (0x80184460, 0x2EC, "func_80184460", "medium"),
    (0x8018474C, 0x15C, "func_8018474C", "verified"),
    (0x801849F0, 0x34, "func_801849F0", "medium"),
    (0x80184A24, 0x16C, "func_80184A24", "medium"),
    (0x80184B90, 0xDC, "func_80184B90", "high"),
    (0x80184C6C, 0x2C, "func_80184C6C", "verified"),
    (0x80184C98, 0xC, "bios_A0_49_GPU_cw", "verified"),
    (0x80184CA8, 0x34, "func_80184CA8", "high"),
    (0x80184CDC, 0x3C, "func_80184CDC", "verified"),
    (0x80184D18, 0x688, "func_80184D18", "verified"),
    (0x80185400, 0x50, "func_80185400", "high"),
    (0x80185450, 0xB4, "func_80185450", "verified"),
    (0x80185504, 0xC, "bios_B0_35_FileWrite", "verified"),
    (0x80185514, 0x30, "func_80185514", "high"),
    (0x801855F0, 0x20, "func_801855F0", "verified"),
    (0x80185CB0, 0x588, "func_80185CB0", "medium"),
    (0x80186238, 0x280, "func_80186238", "medium"),
    (0x801864B8, 0x2CC, "func_801864B8", "medium"),
    (0x80186784, 0x41C, "func_80186784", "low"),
    (0x80186BA0, 0x88, "func_80186BA0", "low"),
    (0x80186C28, 0xE0, "func_80186C28", "high"),
    (0x80186D08, 0xF4, "func_80186D08", "low"),
    (0x80186DFC, 0x50, "func_80186DFC", "medium"),
    (0x80186E4C, 0x1EC, "func_80186E4C", "medium"),
    (0x80187038, 0x16C, "func_80187038", "medium"),
    (0x801871A4, 0x100, "func_801871A4", "low"),
    (0x80187398, 0x50, "func_80187398", "verified"),
    (0x801873E8, 0x50, "func_801873E8", "verified"),
    (0x80187460, 0x20, "func_80187460", "verified"),
    (0x80187480, 0xC, "bios_B0_16_OutdatedPadGetButtons", "verified"),
    (0x801874B0, 0x8C, "func_801874B0", "verified"),
    (0x801875F8, 0x30, "func_801875F8", "verified"),
    (0x80187628, 0x80, "func_80187628", "verified"),
    (0x801876A8, 0x38, "func_801876A8", "verified"),
    (0x80187788, 0xC, "bios_B0_12_InitPad", "verified"),
    (0x80187798, 0xC, "bios_B0_13_StartPad", "verified"),
    (0x801877A8, 0xC, "bios_B0_14_StopPad", "verified"),
    (0x801877B8, 0xC, "bios_B0_15_OutdatedPadInitAndStart", "verified"),
    (0x801877C8, 0xC, "bios_C0_02_SysEnqIntRP", "verified"),
    (0x801877D8, 0xC, "bios_C0_03_SysDeqIntRP", "verified"),
    (0x801877E8, 0x14, "func_801877E8", "low"),
    (0x801877FC, 0x14, "func_801877FC", "low"),
    (0x80187810, 0x68, "func_80187810", "high"),
    (0x80187878, 0x148, "func_80187878", "high"),
    (0x801879C0, 0x9C, "func_801879C0", "verified"),
    (0x80187A5C, 0xC, "bios_C0_0A_ChangeClearRCnt", "verified"),
    (0x80187A6C, 0x30, "func_80187A6C", "high"),
    (0x80187A9C, 0x30, "func_80187A9C", "low"),
    (0x80187ACC, 0x30, "func_80187ACC", "low"),
    (0x80187B60, 0x30, "func_80187B60", "high"),
    (0x80187BC0, 0x10, "func_80187BC0", "low"),
    (0x80187BE8, 0x1C, "func_80187BE8", "high"),
    (0x80187CE0, 0x1E8, "func_80187CE0", "medium"),
    (0x80188150, 0x2C, "func_80188150", "medium"),
    (0x80188184, 0xC, "bios_A0_72_CdRemove", "verified"),
    (0x8018819C, 0xC, "bios_B0_17_ReturnFromException", "verified"),
    (0x801881AC, 0xC, "bios_B0_18_SetDefaultExitFromException", "verified"),
    (0x801881BC, 0xC, "bios_B0_19_SetCustomExitFromException", "verified"),
    (0x801881CC, 0x3C, "func_801881CC", "low"),
    (0x8018824C, 0x58, "func_8018824C", "medium"),
    (0x80188348, 0x2C, "func_80188348", "medium"),
    (0x80188374, 0x50, "func_80188374", "medium"),
    (0x801885F0, 0x2C, "func_801885F0", "medium"),
    (0x80188634, 0x10, "func_80188634", "high"),
]

UNRESOLVED = [
    (0x80180CD8, "jr $10"),
    (0x80180CE8, "jr $10"),
    (0x80180CF8, "jr $10"),
    (0x80180DE4, "jr $10"),
    (0x80180DF4, "jr $10"),
    (0x80180E04, "jr $10"),
    (0x80180E14, "jr $10"),
    (0x80180E8C, "jalr $10"),
    (0x80180F44, "jalr $10"),
    (0x80180FC4, "jr $10"),
    (0x80180FE4, "jalr $10"),
    (0x80181D68, "jalr $2"),
    (0x801820A4, "jalr $2"),
    (0x80182114, "jalr $2"),
    (0x801822C4, "jalr $2"),
    (0x801823CC, "jalr $2"),
    (0x8018271C, "jalr $2"),
    (0x801827C4, "jalr $2"),
    (0x80182A50, "jalr $2"),
    (0x80182C60, "jalr $3"),
    (0x80182C8C, "jalr $3"),
    (0x80182DF8, "jalr $2"),
    (0x8018428C, "jalr $19"),
    (0x801845B4, "jalr $2"),
    (0x80184714, "jalr $2"),
    (0x80184C9C, "jr $10"),
    (0x80185508, "jr $10"),
    (0x801863D0, "jalr $2"),
    (0x80186404, "jalr $2"),
    (0x80186658, "jalr $2"),
    (0x8018668C, "jalr $2"),
    (0x80186AC8, "jalr $2"),
    (0x80186AFC, "jalr $2"),
    (0x80187484, "jr $10"),
    (0x8018778C, "jr $10"),
    (0x8018779C, "jr $10"),
    (0x801877AC, "jr $10"),
    (0x801877BC, "jr $10"),
    (0x801877CC, "jr $10"),
    (0x801877DC, "jr $10"),
    (0x801877F4, "jr $9"),
    (0x80187808, "jr $9"),
    (0x80187824, "jalr $10"),
    (0x80187A60, "jr $10"),
    (0x80187A84, "jalr $2"),
    (0x80187AB4, "jalr $2"),
    (0x80187AE4, "jalr $2"),
    (0x80187B78, "jalr $2"),
    (0x80187DC0, "jalr $2"),
    (0x80188188, "jr $10"),
    (0x801881A0, "jr $10"),
    (0x801881B0, "jr $10"),
    (0x801881C0, "jr $10"),
]

created = renamed = 0
for a, size, name, conf in FUNCS:
    ea = addr(a)
    fn = fm.getFunctionAt(ea)
    if fn is None:
        fn = createFunction(ea, name)
        if fn is not None:
            created += 1
    if fn is not None and not name.startswith("func_"):
        fn.setName(name, SourceType.IMPORTED)
        renamed += 1
    if fn is not None:
        setPlateComment(ea, "psxrecomp: confidence=%s" % conf)

for a, what in UNRESOLVED:
    createBookmark(addr(a), "psxrecomp", "unresolved %s" % what)

print("psxrecomp: %d functions created, %d named, %d unresolved "
      "indirect sites bookmarked" % (created, renamed, len(UNRESOLVED)))
